[repo]
kind = "repo"

# recipes for generating master flats, bias, darks...
[[repo-ref]]
dir = "master_bias"
[[repo-ref]]
dir = "master_dark"
[[repo-ref]]
dir = "master_flat"

# Note: For automated recipe finding, it is important to list more demanding recipes first.  For instance:
# osc_dual_duo (which needs a HaOiii and a SiiOiii filter) should be listed first, so that if we see
# dataset containing both HaOiii and SiiOiii filters we will assume that is the recipe to use.
#
# But later if we see a dataset containing only HaOiii data, assume osc_single_duo should be used.

[[repo-ref]]
dir = "master/bias.toml"

[[repo-ref]]
dir = "master/dark.toml"

[[repo-ref]]
dir = "master/flat.toml"

[[repo-ref]]
dir = "osc/light.toml"

[[repo-ref]]
dir = "osc/light_no_bias.toml"

[[repo-ref]]
dir = "osc/single_duo.toml"

[[repo-ref]]
dir = "osc/dual_duo.toml"

[[repo-ref]]
dir = "osc/osc_simple.toml"

[[repo-ref]]
dir = "seestar"
