[repo]
# Most recipe repos should be of kind "recipe".  However, to the 'default' recipe we host on github we call "std-recipe" at app
# startup the app checks to see if it has at least one "std-recipe", if it doesn't the github hosted version is used automatically.
# You should never need to make a "std-recipe" unless you intend to completely replace this behavior.
kind = "std-recipe"

# Note: For automated recipe finding, it is important to list more demanding recipes first.  For instance:
# osc_dual_duo (which needs a HaOiii and a SiiOiii filter) should be listed first, so that if we see
# dataset containing both HaOiii and SiiOiii filters we will assume that is the recipe to use.
#
# But later if we see a dataset containing only HaOiii data, assume osc_single_duo should be used.

[[repo-ref]]
dir = "master/bias.toml"

[[repo-ref]]
dir = "master/dark.toml"

[[repo-ref]]
dir = "master/flat.toml"

[[repo-ref]]
dir = "osc/light_vs_bias.toml"

[[repo-ref]]
dir = "osc/light_vs_dark.toml"

[[repo-ref]]
dir = "osc/light_no_darks.toml"

[[repo-ref]]
dir = "osc/seqextract_haoiii.toml"

[[repo-ref]]
dir = "osc/single_duo.toml"

[[repo-ref]]
dir = "osc/dual_duo.toml"

[[repo-ref]]
dir = "osc/osc_simple.toml"

[[repo-ref]]
dir = "graxpert/background.toml"

[[repo-ref]]
dir = "graxpert/deconv-obj.toml"

[[repo-ref]]
dir = "graxpert/denoise.toml"

[[repo-ref]]
dir = "common/thumbnail.toml"

[[repo-ref]]
url = "https://raw.githubusercontent.com/geeksville/siril-scripts/refs/heads/main/processing/VeraLux_HyperMetric_Stretch.toml"
