

notes = """
06:45:08: StarNet: running. Please wait...
06:45:08: StarNet: linear mode. Applying Midtone Transfer Function (MTF) pre-stretch to image.
06:45:08: Applying MTF with values 0.026697, 0.018058, 1.000000
06:45:08: StarNet: Reading input image... Done!
06:45:08: StarNet: Bits per sample: 16
06:45:08: StarNet: Samples per pixel: 3
06:45:08: StarNet: Height: 1920
06:45:08: StarNet: Width: 1080
06:45:09: StarNet: Restoring neural network checkpoint... Done!
06:45:09: StarNet: Total number of tiles: 40
06:45:13: StarNet: linear mode. Applying inverse MTF stretch to starless image.
06:45:13: Applying inverse MTF with values 0.026697, 0.018058, 1.000000
06:45:13: Saving FITS: file /home/vscode/starless_bk_stacked.fit, 3 layer(s), 1080x1920 pixels, 32 bits
06:45:13: Saving FITS: file /home/vscode/starmask_bk_stacked.fit, 3 layer(s), 1080x1920 pixels, 32 bits
06:45:13: StarNet: job completed.
06:45:13: Execution time: 4.36 s

starnet [-stretch] [-upscale] [-stride=value] [-nostarmask]
Calls StarNet to remove stars from the loaded image.

Prerequisite: StarNet is an external program, with no affiliation with Siril, and must be installed correctly prior the first use of this command, with the path to its CLI version installation correctly set in Preferences / Miscellaneous.

The starless image is loaded on completion, and a star mask image is created in the working directory unless the optional parameter -nostarmask is provided.

Optionally, parameters may be passed to the command:
- The option -stretch is for use with linear images and will apply a pre-stretch before running StarNet and the inverse stretch to the generated starless and starmask images.
- To improve star removal on images with very tight stars, the parameter -upscale may be provided. This will upsample the image by a factor of 2 prior to StarNet processing and rescale it to the original size afterwards, at the expense of more processing time.
- The optional parameter -stride=value may be provided, however the author of StarNet strongly recommends that the default stride of 256 be used
"""
